name: Publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Java for publishing
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: gradle
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build artifact
        run: ./gradlew check publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}